pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cd ${WORKSPACE}/richards-standalone
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                ./setup_env.sh -n richards-standalone -u
                conda activate richards-standalone
                pip install --no-deps .
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate richards-standalone
                cd ${WORKSPACE}/richards-standalone
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/richards-standalone
                ./setup_env.sh -n richards-standalone -d -u
                conda activate dev-richards-standalone
                pip install --no-deps --editable .
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate dev-richards-standalone
                cd ${WORKSPACE}/richards-standalone
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/richards-standalone
                ./setup_env.sh -n pinned-richards-standalone
                conda activate pinned-richards-standalone
                pip install --no-deps .
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-richards-standalone
                cd ${WORKSPACE}/richards-standalone
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/richards-standalone
                ./setup_env.sh -n pinned-richards-standalone -d
                conda activate pinned-dev-richards-standalone
                pip install --no-deps --editable .
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-richards-standalone
                cd ${WORKSPACE}/richards-standalone
                pytest tests
                '''
            }
        }
    }
}
