name: richards-standalone-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.8
  - astroid=2.12.12
  - asttokens=2.1.0
  - attr=2.5.1
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.10.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfgv=3.3.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - codespell=2.2.2
  - colorama=0.4.6
  - contourpy=1.0.6
  - cryptography=38.0.3
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.6
  - docutils=0.17.1
  - exceptiongroup=1.0.2
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.8.0
  - flake8=5.0.4
  - flake8-black=0.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.21.1
  - gstreamer=1.21.1
  - icu=70.1
  - identify=2.5.8
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=3.3.0
  - iniconfig=1.1.1
  - ipdb=0.13.9
  - ipython=8.6.0
  - isort=5.10.1
  - jack=1.9.21
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lazy-object-proxy=1.8.0
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.4
  - libclang13=15.0.4
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.4
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - libsndfile=1.1.0
  - libsqlite=3.39.4
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - livereload=2.6.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mpg123=1.30.2
  - munkres=1.1.4
  - mypy=0.990
  - mypy_extensions=0.4.3
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - ncurses=6.3
  - nodeenv=1.7.0
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.1
  - parso=0.8.3
  - pathspec=0.10.2
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pre-commit=2.20.0
  - prompt-toolkit=3.0.32
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycodestyle=2.9.1
  - pycparser=2.21
  - pydantic=1.10.2
  - pydocstyle=6.1.1
  - pyflakes=2.5.0
  - pygments=2.13.0
  - pylint=2.15.5
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytoolconfig=1.2.2
  - pytz=2022.6
  - pyyaml=6.0
  - qt-main=5.15.6
  - readline=8.2
  - requests=2.28.1
  - rope=1.4.0
  - rstcheck=6.1.1
  - rstcheck-core=1.0.2
  - scipy=1.9.3
  - setuptools=65.5.1
  - shellingham=1.5.0
  - sip=6.7.4
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=4.3.2
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.39.3
  - stack_data=0.6.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - tornado=6.2
  - traitlets=5.5.0
  - typer=0.4.2
  - types-docutils=0.18.3
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - ukkonen=1.0.1
  - urllib3=1.26.11
  - virtualenv=20.16.7
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xarray=2022.11.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - flake8-pyproject==1.1.0.post0
