channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - click
  - pytest
  - pip
  - numpy
  - xarray
  - matplotlib
  - scipy

  - pip:
    # add pip requirements here if needed.
